### PR TITLE
ledger_cmd: include settings from g:ledger_date_format

### PR DESCRIPTION
**Pull request by rohieb**
vim-ledger understands the option `g:ledger_date_format` which controls the formatting of the journal file. But when ledger tries to read such files, e.g. when calling `ledger#entry()`, it gets confused about the date format. Solve this by adding `g:ledger_date_format` as input and output date formats to the ledger command line.

### CODE REVIEW

**Comment by rohieb** [comment]
I never used hledger, so I cannot say much about it. I guess we could try to find out if `g:ledger_bin` points to a hledger or a ledger-cli (or something else) and then set the right command line arguments (like `--date-format`) for the respective ledger-like. But that sounds like too much unnecessary magic, and the same could be configured explicitly by the user through `g:ledger_extra_options`, probably even in the next line in their config after setting `g:ledger_bin` itself. I didn't think as far as being compatible with other ledger-likes besides ledger-cli, so if you want to drop this PR, I have nothing against it :)

**Comment by alerque** [comment]
For now I think I'd rather let people using non-default date options set this manually in `g:ledger_extra_options` themselves rather than break `hledger` usage entirely. As it stands this would require people to fork and modify the plugin to get `hledger` working again, and I don't want to see that happen.

I think I'll sit on the PR for the moment until I get my head around a better way to explicitly support both alternatives.

**Comment by alerque** [comment]
Hey @rohieb as of #88 I added some basic detection of `hledger` so that proper arguments can be passed on depending on what ledger variant is being used. You can see an example of this in the descriptions vs. payees snafu I fixed there.

Can you rebase this and use the `g:ledger_is_hledger` flag to set these options just for `ledger`? I'd be happy to accept this and get it in me main plugin for everybody as soon as it doesn't break `hledger` users usage. Thanks!

**Comment by rohieb** [comment]
You asked me to rebase these changes, but now you've merged them… was that by accident, or did you change your mind?

**Pull request merged**
