### PR TITLE
Disable spell highlighting for an amounts.

### PR DESCRIPTION
**Pull request by abobov**

### CODE REVIEW

**Comment by alerque** [comment]
Thanks for taking the time to contribute this @abobov. I realize it has been a long time since you posted this, but I've recently stepped in to help maintain this plugin and hope to see this integrated. That being said I have some questions about the code if you're still around...

**Comment by abobov** [comment]
@alerque Yes, for me it is more reasonable to disable spell check by default, I just tried to keep behavior as-is by default.

**Comment by alerque** [comment]
Keeping default behavior in general is a good goal, but in this case I think it would be safe and advisable to go ahead and make the default be _not_ spell checking the commodities/amounts. This reduces the load of things we expect people to do for a sane config. I think the desire for the opposite behavior will be trivial to non-existent.

Would you be willing to make the change and update this PR?

**Comment by alerque** [comment]
Thanks again for the contribution and for being willing to touch it up for merger even years later.

**Pull request merged**
